### ISSUE TITLE
why it showing this

### ISSUE THREAD

**Issue by dhananjay1410** [gtmray/Portfolio-Management-System#6]
python -u "c:\Users\Asus\Downloads\Portfolio Management System-20221127T171635Z-001\Portfolio Management System\tempCodeRunnerFile.py"
Traceback (most recent call last):
  File "c:\Users\Asus\Downloads\Portfolio Management System-20221127T171635Z-001\Portfolio Management System\tempCodeRunnerFile.py", line 1, in <module>
    db = yaml.load(open('db.yaml'))
NameError: name 'yaml' is not defined

**Comment by gtmray** [comment]
The yaml file contains passwords and keys for the database. So, it's ignored in gitignore.

**Comment by Dhenu-Sarang** [comment]
even i am facing the same error. Please tell me how to fix it . I need to fix it as soon as possible
